var MyBiblicalDiary_json = 
{
    "2021": {
        "0113": "trt",
        "0106": "uu<ol><li>ui</li><li>oop</li></ol>",
        "0105": "addd",
        "0103": "new year eve"
    },
    "2022": {
        "1107": "<span style=\"-webkit-text-size-adjust: auto; font-family: Times; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;\">Jesus did not recommend us to take part in politics. But He did not imply politicians are evil. <br>Politics is like money. It can be used for both good and evil.<br>Through politics, we can better understand the world God created. Politics is a layer of heaven above money.&nbsp; God created many heavens.&nbsp;<br>Christians need to know politics but should not be addicted to it.&nbsp;<br>Through understand the politics, we can know the sign of the world, the will of God, to testify what Jesus ever said to us, the power of Jesus.-- no matter what your career is, as long as you work for the kingdom of God, you are the disciple of him.&nbsp;<br></span><br><br>How do Christians live under a dictatorship ruler without freedom of speech?&nbsp;<br>(1) political resistance&nbsp;<br>(2) hun (abide)<br>(3) run&nbsp;<br>(4) dsd",
        "1108": "Anger makes things worse. Let Jesus do it.&nbsp;",
        "1109": "-don’t be against enemies. But against to myself. Attach self body. &nbsp;Let my body abide me.&nbsp;<br>Love your enemies,&nbsp;<br><br><br>Chinese language is a ambiguous language. Interpretation can be many but contradictory each other.&nbsp;<br><br>But the elements of composition are identical to biblical.&nbsp;<br><br>Eg. People took food for heaven.&nbsp;",
        "1110": "-don’t be against enemies&nbsp;<div>-but love your enemies. How?</div><div><br></div><div>Jx: then no enemies in the world.&nbsp;</div><div>Wd: there is only one struggle—believe him or not.&nbsp;</div>",
        "1113": "- Why does Jewish race keep low in population among world? &nbsp;It’s a form of the role in leadership.&nbsp;<br><br>- those who were reborn imply that they get out of the world. But firstly they must get of of their culture where they were born.&nbsp;<br><br>Some of the cultures are easier than the other to get rid of.&nbsp;<br><br>The difference languages are created by God.&nbsp;<br>It’s role is to help man under stand the plural of heaven.&nbsp;<br><br><br>",
        "1114": "-Jesus is the Holy Spirit.&nbsp;<ol><li>Jesus miracle prove he is a spirit.&nbsp;</li><li>Jesus words prove he is a spirit.&nbsp;</li><li>The Word became the flesh.&nbsp;</li></ol>",
        "1115": "<ol><li>Faith=&gt;Honest heart =&gt;naive=&gt; Simple. </li><li>Politics is completely complicated. Pre tended to a good man, pretended to be a bad man. The real contains fake, the fake contains real. Repeated unlimited. But God know everything. </li><li>Christians must accept a fact that the world become worse and the kingdom of God become greater. </li><li>The western democracy system will be destroyed by the east dragon.  But the kingdom of Heaven will reach to the end of the earth. </li><li>Nerve connects to God. Do not Let our nerve connect to the world.&nbsp;</li></ol>",
        "1116": "Dennis lead <ol><li>Greg: the separated family children. Pray for them. </li><li>ding: mom. Patience.&nbsp;</li><li>Jerry: to Lexington. Her Roommate plan the baptism. Help church event.&nbsp;</li><li>Dennis: being content. Consultant. Phil Lan. Video conference &nbsp;</li></ol>",
        "1117": "Uo00p",
        "1122": "<br>",
        "1123": "Pc off",
        "1127": "The story of the Jesus is the story above all stories.&nbsp;",
        "1129": "<br>",
        "1130": "WD lead&nbsp;",
        "1214": "P141, 7:00 pm. ",
        "1218": "<span style=\"font-family: -webkit-standard; font-size: medium; background-color: rgb(250, 235, 215);\">as</span><br style=\"font-family: -webkit-standard; background-color: rgb(250, 235, 215);\"><br style=\"font-family: -webkit-standard; background-color: rgb(250, 235, 215);\"><span style=\"font-family: -webkit-standard; font-size: medium; background-color: rgb(250, 235, 215);\">Contrast the stability of the handbook to the venerable of the inscriptions, &nbsp;</span><br style=\"font-family: -webkit-standard; background-color: rgb(250, 235, 215);\"><br style=\"font-family: -webkit-standard; background-color: rgb(250, 235, 215);\"><span style=\"font-family: -webkit-standard; font-size: medium; background-color: rgb(250, 235, 215);\">Rich Gospel information can be extracted from every pictograph, but none of them is new for us today from the biblical perspective.&nbsp;</span>",
        "1221": "P153, Spiri<div>Dennis: sister (Larry) sick. Brother. Infortri passion.&nbsp;</div><div>Christians eve dinner.&nbsp;</div><div><br></div><div>Wei: &nbsp;Charlie.&nbsp;</div><div><br></div><div>Jerry. Coco each trip. Brother in law (shops life)</div><div><br></div><div>Jerry: &nbsp;new grand daughter. Bradly-cachy (son).&nbsp;</div><div>Friends separated (Kids).&nbsp;</div><div><br></div>",
        "1224": "64 not only see the essence of ccp but also it’s culture, it’s peoples.&nbsp;<div><br></div><div>Mile Yu has his right to love Chinese culture though ccp deprived him.&nbsp;</div><div><br></div>",
        "1226": "Love totes: fasten, invisible&nbsp;",
        "0105": "as<br><br>Contrast the stability of the handbook to the venerable of the inscriptions, &nbsp;<br><br>Rich Gospel information can be extracted from every pictograph, but none of them is new for us today from the biblical perspective.&nbsp;"
    },
    "2023": {
        "0104": "700pm&nbsp;<div>p165</div><div>Dennis: courses presentation. conversation. Brother-in-law health.&nbsp;</div><div>Jerry: church member tumor, 2nd cancer treatment.&nbsp;</div><div>Wei: covid-19 recovery</div><div>Greg: Bradly (son), Sister.&nbsp;&nbsp;</div>",
        "0120": "Flight&nbsp;",
        "0111": "700pm<div>Man and woman created equally:</div><div>1. Passively </div><div>2. Image of god</div><div>3. Purpose is the same: manage earth. </div><div>4. Providence is the same. Same food. </div><div><br></div><div>How different </div><div>1. Sequence </div><div>2. Closeness to god. </div><div>3. </div><div><br></div><div>pray request:</div><div>dennis: 2 sisters, nephews. </div><div>jerry: lexin</div><div>greg: retreat. orlando, disciple.</div><div><br></div><div><br></div><div><br></div><div><br></div>",
        "0118": "p195.&nbsp;<div>Jerry: lexing, fellowship</div><div>Dennis: \"God is not dead.\"&nbsp; Unintended selfish.</div><div><br></div><div>Ding: Thanks God for recovery. Continue pray for this family be blessed and glory God, fellow Jesus.</div><div><br></div><div><br></div><div><br></div>",
        "0202": "10:am<div>P210. Col 3:19</div><div>Gary: pray for Susan, cathlic, adop child for single mom. Bro passed away.</div><div>wied: </div><div>Dennis: a guy Nilson, pikness. recarnation. hechritan, salvation, kidnyes,&nbsp;</div><div>Jerry: Yiling's bros &amp; sis.</div><div><br></div>",
        "0209": "10am, p222, eph5:33, Greg Testimony.<div>Dennis: grandson Ryla.<br>Nelson, Jeff and Randy, Joe,&nbsp;</div><div>Greg: Suson bro passed away. wisdom to share with her. Ross.</div><div><br><div><br><div><br><div><br><div><br><div><div><br></div></div></div></div></div></div></div>",
        "0223": "wei i min testi.<div>wei: control temp</div><div>Jerry:1) 2) church retreat. </div><div>D: nelson</div><div>G: susan's family.&nbsp; &nbsp;<br><div><br><div><br></div></div></div>",
        "0216": "Jerry testimony. defer.<div>Dennis: Nelson. Adams Drews, in church.</div><div>Jerry: trip&nbsp;</div><div>WD: pray for the safe trip, and wisdom of preaching, control the amygadala.&nbsp;</div><div>Greg: Susan Sunday memorial service. greving process.&nbsp;</div><div>comfort Ross. 10,12 sons.&nbsp;<br><div><br><div><br><div><br></div></div></div></div>",
        "0309": "1 min testimony.<div><br></div>",
        "0220": "BEijing arrived.&nbsp;",
        "0221": "XieHe hospital&nbsp;",
        "0222": "xh",
        "0227": "Qhong am eye appt<div><br></div>",
        "0301": "<div>Eye surgery&nbsp;</div>1pm physical exam",
        "0302": "8pm. p259.<div>Dennis: teenage girl to serve.&nbsp;</div><div>Jerry: Lexing: peace in her heart.<br>Greg: Friend, morning process.</div><div><br></div><div>In Pursuit of a Biblical World View 1 of 2.pdf</div><div><br><div><br></div></div>",
        "0225": "Zhao Gang",
        "0224": "Eye exam.&nbsp;",
        "0228": "Pm teeth 721",
        "0303": "<br>",
        "0307": "Eye surgery.&nbsp;",
        "0306": "Nicole test. ",
        "0314": "Jx followup",
        "0313": "2pm teeth",
        "0316": "skip",
        "0405": "Jx exame",
        "0318": "Wd eye test&nbsp;",
        "0323": "p271, psa8:3-5.<div>Jerry: Yiling healing.</div><div>Dennis: <br>Mentaling relationship w/ Mareay. coatch world; Trip to Yellow Stone/Cannon; Nelson reachout; Miler child membership; <br>Ding: <br>Greg: Susan who lost brother, growing the process of recovery.  Nephew maltreatment.  <br><br></div><div><br></div><div><div><br></div></div>",
        "0330": "p285, 2 of 2 pdf<br>Dennis:Nelson.<br>Jerry:school work for Lexing,",
        "0406": "skip",
        "0413": "p293, 2. <div>jx medicine taken lzxdjn</div>",
        "0510": "王国伟 中医科",
        "0419": "Jx eye",
        "0420": "p307.<div>last unit of class. </div><div>Weid: The power of association.</div><div>avogah.Gen2:15.&nbsp;</div><div><br></div><div>cultures are not morally neutral. (p314)</div><div>Jerry: health condition,moving. God's will be done.</div><div>Dennis: Knee x-ray, phys therapy.</div><div>-Brandy international coach. new coach cowork.&nbsp;</div><div>-invitation of Brandson, Rily.&nbsp; JHi, question.&nbsp;</div><div>Greg:</div><div>-last weekend.</div><div>-new headmaster. primary school. pca elder.</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>",
        "0427": "unit1<div>I happen to talk with a seller who is about 70. She is talkative. And she tried to convert me to be Buddhism.&nbsp;</div><div>She asked me: what do you think of Buddhism? &nbsp;</div><div>I said: “I said I don’t want to offend you.”&nbsp;</div><div><br></div><div>She said: “don’t matter.”&nbsp;</div><div>“Buddhism is confusing”</div><div><br></div><div>She said: “Buddha is about the heart. You can say this way, he can say that way. All are correct. Buddhist teach us friendship, kindness, love. do not hurt each others. Life is short and pain why we hurt each others. Why not be happy with each others in short life.”&nbsp;</div><div>She want to send me a Buddhism book to read.&nbsp;</div><div>She also told me that she got covid but was healed by taking some medicine in three days.”</div><div><br></div><div><div>“Do you believe in the after life?”</div><div>“No, everything is gone after death.”</div></div><div><br></div><div>I asked her: “have you ever heard of Jesus?”</div><div>She said: “yes, Jesus was nailed on cross and died for us. All religions are teaching people to be a good one. We do things base up our consciousness.”</div><div><br></div><div>I said: “you looks like a well educated knowledges person.”</div><div><br></div><div>She said: “no. I only have three years elementary education. I worked in railways system of state governments.” &nbsp;</div><div><br></div><div><br></div><div><br></div><div>I showed mercy on her. And pointing to the Buddha idols with oranges offering.&nbsp;</div><div>I told her that: “God hate people to worship idols. You should not worship idols.”&nbsp;</div><div><br></div><div>She began to be upset and said: “the idol is myself. Every one is Buddha.” And began to bush me away from the idols. She afraid that my saying could offend the Buddha.&nbsp;</div><div><br></div><div>I felt that it is hard for me to preach gospels to her. I only pray God mercy on us.&nbsp;</div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div><div><br></div>",
        "0525": "Weid Unit 5. power of association.",
        "0429": "3:30pm dental&nbsp;",
        "0423": "I could not find people selling the turtles on the street in front of the Buddha temple.&nbsp;<div>All people suddenly appeared and suddenly gone triggered me to think selling turtles is probably related to the Easter Day.&nbsp;</div><div><br></div><div>In a Buddha shop, I talked with the seller. “Do you really believe in Buddhism?”</div><div><br></div><div>He hesitated: “I believe in my consciousness.”&nbsp;</div><div>I got a little bit comfort. I told him that I am interested in the incense. He told me that he used to work in incense factory. To collect the raisins and other fragrances herbs first. Then grinding them to become the powders very fine. Then use the thick wine to make the burning incense.”</div><div><br></div><div>He also gave me several pieces of raisins for free.&nbsp;</div><div><br></div><div>I felt gratitude. May God show mercy on him.&nbsp;</div><div><br></div><div><br></div><div><br></div><div><br></div>"
    }
}